import { test } from "node:test";
import assert from "node:assert/strict";

import * as pypi from "../src/ecosystems/pypi.mjs";
import { diffEntries } from "../src/diff.mjs";

const POETRY = `# This file is automatically @generated by Poetry.

[[package]]
name = "requests"
version = "2.32.3"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.8"
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:abc123"},
    {file = "requests-2.32.3.tar.gz", hash = "sha256:def456"},
]

[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library"
optional = false
python-versions = ">=3.8"
files = [
    {file = "urllib3-2.2.1.tar.gz", hash = "sha256:fff999"},
]

[metadata]
lock-version = "2.0"
`;

const UV = `version = 1

[[package]]
name = "requests"
version = "2.32.3"
source = { registry = "https://pypi.org/simple" }
sdist = { url = "https://files.pythonhosted.org/x/requests-2.32.3.tar.gz", hash = "sha256:def456" }

[[package]]
name = "evil"
version = "0.0.1"
source = { git = "https://github.com/attacker/evil.git" }
`;

test("parses poetry.lock packages + hashes", () => {
  const e = pypi.parse(POETRY, "poetry.lock");
  assert.equal(e["requests"].version, "2.32.3");
  assert.equal(e["requests"].source, "pypi");
  assert.equal(e["requests"].integrity, "sha256:abc123");
  assert.equal(e["urllib3"].version, "2.2.1");
});

test("parses uv.lock and flags git source", () => {
  const e = pypi.parse(UV, "uv.lock");
  assert.equal(e["requests"].version, "2.32.3");
  assert.equal(e["requests"].source, "pypi");
  assert.equal(e["evil"].source, "git");
  assert.equal(pypi.isRegistryBacked(e["evil"]), false);
});

test("parses pinned requirements.txt, ignores unpinned lines", () => {
  const req = `# comment
requests==2.32.3 --hash=sha256:def456
flask>=2.0       # range, not analyzable
django==5.0.1
-r other.txt
`;
  const e = pypi.parse(req, "requirements.txt");
  assert.equal(e["requests"].version, "2.32.3");
  assert.equal(e["requests"].integrity, "sha256:def456");
  assert.equal(e["django"].version, "5.0.1");
  assert.equal(e["flask"], undefined);
});

test("normalizes package name per PEP 503 for the registry key", () => {
  const e = pypi.parse(`[[package]]\nname = "Django_REST.framework"\nversion = "1.0.0"\n`, "uv.lock");
  const key = Object.keys(e)[0];
  assert.equal(pypi.packageKey(e[key], key), "django-rest-framework");
});

test("diff detects an upgrade", () => {
  const before = pypi.parse(POETRY, "poetry.lock");
  const after = pypi.parse(POETRY.replace('version = "2.2.1"', 'version = "2.2.2"').replace("sha256:fff999", "sha256:newhash"), "poetry.lock");
  const diff = diffEntries(before, after);
  assert.deepEqual(diff.changed.map((c) => c.name), ["urllib3"]);
});
